---
namespace: dubzland
name: minio
version: "1.1.0"
readme: README.md
authors:
  - Josh Williams <jdubz@dubzland.com>
description: Installs and configures the Minio Object Storage server and client.
license_file: COPYING
tags:
  - linux
  - debian
  - ubuntu
  - minio

dependencies:
  "community.general": "*"

repository: https://git.dubzland.com/dubzland/ansible-collections/minio

# The URL to any online docs
documentation: |
  https://docs.dubzland.io/ansible-collections/collections/dubzland/minio/

# The URL to the homepage of the collection/project
homepage: https://git.dubzland.com/dubzland/ansible-collections/minio

# The URL to the collection issue tracker
issues: https://git.dubzland.com/dubzland/ansible-collections/minio/-/issues
build_ignore:
  - .ansible-lint
  - .cache
  - .gitignore
  - .gitlab-ci.yml
  - .venv
  - .yamllint
  - requirements-*.txt
  - extensions
