---
namespace: dubzland
name: minio
# TODO: Bump to 1.0 when modules complete
version: 0.0.1  # noqa: galaxy[version-incorrect]
readme: README.md
authors:
  - Josh Williams <jdubz@dubzland.net>
description: Installs and configures the Minio Object Storage server and client.
license:
  - MIT
tags:
  - linux
  - debian
  - ubuntu
  - minio

dependencies:
  'community.general': '*'

repository: https://git.dubzland.net/dubzland/ansible-collection-minio

# The URL to any online docs
documentation: https://git.dubzland.net/dubzland/ansible-collection-minio

# The URL to the homepage of the collection/project
homepage: https://git.dubzland.net/dubzland/ansible-collection-minio

# The URL to the collection issue tracker
issues: https://git.dubzland.net/dubzland/ansible-collection-minio/-/issues
build_ignore:
  - .ansible-lint
  - .cache
  - .gitignore
  - .gitlab-ci.yml
  - .venv
  - .yamllint
  - requirements-*.txt
  - extensions
