---
- name: Converge
  hosts: all
  tasks:
    - name: Install Server
      ansible.builtin.include_role:
        name: dubzland.minio.minio_server
    - name: Install Client
      ansible.builtin.include_role:
        name: dubzland.minio.minio_client
    - name: Add an alias
      dubzland.minio.minio_alias:
        name: localhost
        url: 'http://localhost:9000'
        access_key: minioadmin
        secret_key: minioadmin
        state: present
    - name: Add a policy
      dubzland.minio.minio_policy:
        name: testing
        data: |
          {
            "Version": "2012-10-17",
            "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                      "s3:ListAllMyBuckets"
                  ],
                  "Resource": [
                      "arn:aws:s3:::*"
                  ]
                }
            ]
          }
        access_key: minioadmin
        secret_key: minioadmin
        minio_url: 'http://localhost:9000'
        state: present
