---
- name: Converge
  hosts: all
  tasks:
    - name: Install Server
      ansible.builtin.include_role:
        name: dubzland.minio.minio_server
    - name: Install Client
      ansible.builtin.include_role:
        name: dubzland.minio.minio_client
    - name: Add an alias
      dubzland.minio.minio_alias:
        name: localhost
        url: 'http://localhost:9000'
        access_key: minioadmin
        secret_key: minioadmin
        state: present
