---
- name: Ensure the Minio system group exists
  ansible.builtin.group:
    name: "{{ minio_server_system_group }}"
    system: true
    state: present

- name: Ensure the Minio system user exists
  ansible.builtin.user:
    name: "{{ minio_server_system_user }}"
    system: true
    create_home: false
    group: "{{ minio_server_system_group }}"
    state: present

- name: Ensure the Minio storage directory exists
  ansible.builtin.file:
    path: "{{ minio_server_storage_dir }}"
    state: directory
    owner: "{{ minio_server_system_user }}"
    group: "{{ minio_server_system_group }}"
    mode: '0770'

- name: Ensure the Minio binary is present
  ansible.builtin.get_url:
    url: "{{ minio_server_binary_url }}"
    dest: "{{ minio_server_binary_path }}"
    owner: root
    group: root
    mode: '0775'

- name: Ensure the Minio systemd unit exists
  ansible.builtin.template:
    src: lib/systemd/system/minio.service.j2
    dest: /lib/systemd/system/minio.service
    owner: root
    group: root
    mode: '0644'
  notify: Enable Minio

- name: Trigger handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure the Minio configuration file exists
  ansible.builtin.template:
    src: etc/default/minio.j2
    dest: /etc/default/minio
    owner: root
    group: root
    mode: '0640'
  notify: Restart Minio

- name: Ensure Minio is running
  ansible.builtin.systemd:
    name: minio
    state: started
