---
argument_specs:
  main:
    short_description: >-
      Installs and configures the L(Minio,https://min.io) server.
    description:
      - Downloads the Minio server binary (B(minio)).
      - Creates a system user and group for running the Minio service.
      - Adds a systemd unit for managing the Minio service.
      - Creates a minimal Minio server configuration.
      - Initializes the Minio installation with an administrative user.
    options:
      minio_server_system_group:
        type: str
        required: false
        description: Service group for the Minio service.
        default: minio
      minio_server_system_user:
        type: str
        required: false
        description: Service user for the Minio service.
        default: minio
      minio_server_binary_url:
        type: str
        required: false
        description: URL used to download the Minio server binary.
        default: https://dl.min.io/server/minio/release/linux-amd64/minio
      minio_server_binary_path:
        type: path
        required: false
        description: Local filename for the Minio server binary.
        default: /usr/local/bin/minio
      minio_server_storage_dir:
        type: path
        required: false
        description: Local directory to contain all Minio server blobs.
        default: /srv/minio
      minio_server_admin_username:
        type: str
        required: false
        description: Account used to access the Web GUI and cli.
        default: minioadmin
      minio_server_admin_password:
        type: str
        required: false
        description: Password associated with O(minio_server_admin_username).
        default: minioadmin
      minio_server_url:
        type: str
        description: External URL used to access the server.
      minio_server_browser_redirect_url:
        type: str
        description: External URL used to access the Minio web console.
      minio_server_opts:
        type: str
        description: Additional options to pass to the Minio service.
